lint

diff --git a/scripts/setup-rust b/scripts/setup-rust
--- a/scripts/setup-rust
+++ b/scripts/setup-rust
@@ -7,15 +7,15 @@ SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "$SCRIPTS_DIR/.."
 
 function run() {
-  echo 1>&2 "running $@"
+  echo 1>&2 "running $*"
   rc=0 && "$@" || rc="$?"
   if ! [ "$rc" -eq 0 ]; then
-    echo 1>&2 "Bootstrap command failed: $@"
+    echo 1>&2 "Bootstrap command failed: $*"
     exit "$rc"
   fi
 }
 
-rust_version=$(cat ./rust-toolchain.toml | sed -n 's/^channel[[:space:]]*=[[:space:]]"\(.*\)"/\1/p')
+rust_version=$(sed -n 's/^channel[[:space:]]*=[[:space:]]"\(.*\)"/\1/p' rust-toolchain.toml)
 echo "using rust version '$rust_version'"
 
 # here we set the toolchain to 'none' and rustup will pick up on ./rust-toolchain.toml
